name: Statistics

on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Execute script
        run: python ./Roadmap/stats.py
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update statistics
          commit_user_name: LeoPincle [github actions]
          commit_user_email: leo.soto965@gmail.com
          commit_author: LeoPincle
